// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import nodecfdiConfig from '@nodecfdi/eslint-config';

const config = nodecfdiConfig(import.meta.dirname, {
  "vitest": true,
  "n": true,
  "projectService": {
    "allowDefaultProject": [
      "*.js",
      "drizzle.config.ts"
    ],
    "defaultProject": "tsconfig.dev.json"
  },
  "sonarjs": true,
  "ignores": {
    "additional": [
      "vitest.config.ts"
    ]
  }
});

export default config.defineConfig(
  {"files":["drizzle.config.ts"],"rules":{"import-x/no-unassigned-import":"off"}},
);
