// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import nodecfdiConfig from '@nodecfdi/eslint-config';

const config = nodecfdiConfig(import.meta.dirname, {
  "vitest": true,
  "n": true,
  "sonarjs": true,
  "ignores": {
    "additional": [
      "vitest.config.ts"
    ]
  },
  "projectService": {
    "allowDefaultProject": [
      "*.js"
    ],
    "defaultProject": "tsconfig.dev.json"
  }
});

export default config.defineConfig(
  {"rules":{"sonarjs/constructor-for-side-effects":"off"}},
);
